services:
  apigateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - userservice
      - orderservice
      - tempo
    environment:
      - ASPNETCORE_URLS=http://+:8082
      - OTEL_SERVICE_NAME=apigateway
      - OTEL_RESOURCE_ATTRIBUTES=service.name=apigateway,service.version=1.0.0
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_DOTNET_AUTO_TRACES_ENABLED=true
      - OTEL_DOTNET_AUTO_METRICS_ENABLED=true
      - OTEL_DOTNET_AUTO_LOGS_ENABLED=true
    networks:
      - tracing-network
    labels:
      - "logging=promtail"
      - "logging_jobname=ApiGateway"

  userservice:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - orderservice
      - tempo
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - OTEL_SERVICE_NAME=userservice
      - OTEL_RESOURCE_ATTRIBUTES=service.name=userservice,service.version=1.0.0
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_DOTNET_AUTO_TRACES_ENABLED=true
      - OTEL_DOTNET_AUTO_METRICS_ENABLED=true
      - OTEL_DOTNET_AUTO_LOGS_ENABLED=true
    networks:
      - tracing-network
    labels:
      - "logging=promtail"
      - "logging_jobname=UserService"

  orderservice:
    build:
      context: ./OrderService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - tempo
      - postgres
    environment:
      - ASPNETCORE_URLS=http://+:8081
      - OTEL_SERVICE_NAME=orderservice
      - OTEL_RESOURCE_ATTRIBUTES=service.name=orderservice,service.version=1.0.0
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_DOTNET_AUTO_TRACES_ENABLED=true
      - OTEL_DOTNET_AUTO_METRICS_ENABLED=true
      - OTEL_DOTNET_AUTO_LOGS_ENABLED=true
    networks:
      - tracing-network
    labels:
      - "logging=promtail"
      - "logging_jobname=OrderService"

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"
    networks:
      - tracing-network

  postgres:
    image: postgres:15.5
    environment:
      - POSTGRES_DB=orderdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tracing-network

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-data:/loki
    networks:
      - tracing-network

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    networks:
      - tracing-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana-data:/var/lib/grafana
    depends_on:
      - tempo
      - loki
    networks:
      - tracing-network

volumes:
  tempo-data:
  grafana-data:
  postgres-data:
  loki-data:

networks:
  tracing-network:
    driver: bridge