{
 "title": "HTTP Client Response Time Dashboard",
 "tags": [ "apm" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Client Response Time by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_client_request_duration_seconds_bucket[5m])) by (le, service_name))",
     "legendFormat": "P50 - {{service_name}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_client_request_duration_seconds_bucket[5m])) by (le, service_name))",
     "legendFormat": "P95 - {{service_name}}"
    }
   ]
  },
  {
   "title": "P95 HTTP Client Response Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_client_request_duration_seconds_bucket[5m])) by (le, service_name))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "HTTP Request Rate by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_client_request_duration_seconds_count[5m])) by (service_name)",
     "legendFormat": "{{service_name}}"
    }
   ]
  }
 ]
}