# apiVersion: v1
# kind: Service
# metadata:
#   name: alloy
#   namespace: monitoring
# spec:
#   selector:
#     app: alloy
#   ports:
#     - name: otlp-grpc
#       port: 4317
#       targetPort: 4317
#     - name: otlp-http
#       port: 4318
#       targetPort: 4318
#     - name: faro
#       port: 12347
#       targetPort: 12347
#   type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: alloy-nodeport
  namespace: monitoring
spec:
  selector:
    app: alloy
  ports:
    - name: faro
      port: 12347
      targetPort: 12347
      nodePort: 30347
  type: NodePort