---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 9.2.10
    chart: grafana
    helm:
      releaseName: grafana
      dashboardsConfigMaps:
        default: "grafana-dashboards"
      values: |
        imageRenderer:
          enabled: true
        grafana.ini:
          dataproxy:
            timeout: 600
            keep_alive_seconds: 600
            row_limit: 10000000
        dashboards:
          default:
            - name: "Kubernetes cluster monitoring"
              datasource: "Prometheus"
              type: "grafana"
              url: "https://grafana.com/grafana/dashboards/6417"
            - name: "Kubernetes Deployment metrics"
              datasource: "Prometheus"
              type: "grafana"
              url: "https://grafana.com/grafana/dashboards/10759"
            - name: "Kubernetes Node monitoring (via Prometheus node-exporter)"
              datasource: "Prometheus"
              type: "grafana"
              url: "https://grafana.com/grafana/dashboards/1860"
            - name: "Kubernetes Pod metrics"
              datasource: "Prometheus"
              type: "grafana"
              url: "https://grafana.com/grafana/dashboards/10939"
            - name: "Kubernetes StatefulSet metrics"
              datasource: "Prometheus"
              type: "grafana"
              url: "https://grafana.com/grafana/dashboards/7149"
        plugins:
          - grafana-piechart-panel
          - grafana-worldmap-panel
          - grafana-polystat-panel
          - grafana-clock-panel
          - grafana-simple-json-datasource
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Loki
                type: loki
                access: proxy
                isDefault: false
                url: http://loki-distributed-gateway
                jsonData:
                  timeout: 600
                  maxLines: 1000
                  minTime: null
                  timeFormat: iso
        
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
