apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-loki-distributed
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 0.80.5
    chart: loki-distributed
    helm:
      releaseName: loki-distributed
      parameters:
        - name: "compactor.enabled"
          value: "true"
        - name: "indexGateway.enabled"
          value: "false"
        - name: "memcachedChunks.enabled"
          value: "false"
        - name: "memcachedFrontend.enabled"
          value: "false"
        - name: "memcachedIndexQueries.enabled"
          value: "false"
        - name: "memcachedIndexWrites.enabled"
          value: "false"
        - name: "queryScheduler.enabled"
          value: "true"
        - name: "queryFrontend.enabled"
          value: "true"
        - name: "serviceMonitor.enabled"
          value: "false"
      values: |
        serviceAccount:
          create: true
        compactor:
          kind: Deployment
        ingester:
          persistence:
            enabled: false
        querier:
          persistence:
            enabled: false
        queryScheduler:
          replicas: 1
        loki:
          config: |
            auth_enabled: false
            chunk_store_config:
              chunk_cache_config:
                embedded_cache:
                  enabled: true
              max_look_back_period: 0s
            distributor:
              ring:
                kvstore:
                  store: memberlist

            ingester:
              chunk_block_size: 262144
              chunk_encoding: snappy
              chunk_idle_period: 30m
              chunk_retain_period: 1m
              lifecycler:
                ring:
                  kvstore:
                    store: memberlist
                  replication_factor: 1
              max_transfer_retries: 0
              wal:
                dir: /var/loki/wal
            ingester_client:
              grpc_client_config:
                grpc_compression: gzip
            common:
              compactor_address: http://loki-distributed-compactor:3100
            compactor:
              shared_store: filesystem
              retention_enabled: false
            limits_config:
              max_query_parallelism: 2
              enforce_metric_name: false
              max_cache_freshness_per_query: 10m
              reject_old_samples: true
              reject_old_samples_max_age: 168h
              split_queries_by_interval: 30m
              retention_period: 0s
              ingestion_rate_mb: 20
              ingestion_burst_size_mb: 30
              query_timeout: 10m
              max_stats_cache_freshness: 60m
              min_sharding_lookback: 5m
              deletion_mode: disabled
            memberlist:
              join_members:
              - loki-distributed-memberlist
            frontend:
              compress_responses: true
              log_queries_longer_than: 5s
              scheduler_address: loki-distributed-query-scheduler:9095
              tail_proxy_url: http://loki-distributed-querier:3100
            frontend_worker:
              scheduler_address: loki-distributed-query-scheduler:9095
            querier:
              max_concurrent: 2
            query_scheduler:
              max_outstanding_requests_per_tenant: 1000
            ruler:
              ring:
                kvstore:
                  store: memberlist

            query_range:
              align_queries_with_step: true
              cache_results: false
              max_retries: 2
            runtime_config:
              file: /var/loki-distributed-runtime/runtime.yaml
            schema_config:
              configs:
              - from: "2023-01-05"
                index:
                  period: 24h
                  prefix: index_
                object_store: filesystem
                schema: v12
                store: boltdb-shipper
            server:
              http_listen_port: 3100
            storage_config:
              boltdb_shipper:
                active_index_directory: /var/loki/index
                cache_location: /var/loki/cache
                cache_ttl: 168h
                shared_store: filesystem
              filesystem:
                directory: /var/loki/chunks
            table_manager:
              retention_deletes_enabled: false
              retention_period: 0s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true