# tempo-traces-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-traces-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard