apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo-distributed
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.8.2
    chart: tempo-distributed
    helm:
      releaseName: tempo-distributed
      parameters:
        - name: "memcached.enabled"
          value: "false"
        - name: "minio.enabled"
          value: "false"
      values: |
        serviceAccount:
          create: true
        distributor:
          replicas: 1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
        ingester:
          replicas: 1
          persistence:
            enabled: false
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
        querier:
          replicas: 1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
        queryFrontend:
          replicas: 1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
        compactor:
          replicas: 1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
        gateway:
          replicas: 1
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
        config:
          retention: 24h
          storage:
            trace:
              backend: local
              local:
                path: /var/tempo/traces
              wal:
                path: /var/tempo/wal
          server:
            http_listen_port: 3200
            grpc_listen_port: 9095
          distributor:
            receivers:
              otlp:
                protocols:
                  grpc:
                    endpoint: 0.0.0.0:4317
                  http:
                    endpoint: 0.0.0.0:4318
          ingester:
            max_block_duration: 5m
          compactor:
            compaction:
              block_retention: 24h
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true