apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo-distributed
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.46.4
    chart: tempo-distributed
    helm:
      releaseName: tempo-distributed
      values: |
        ingester:
          replicas: 1
          persistence:
            enabled: false
        distributor:
          replicas: 1
        querier:
          replicas: 1
        queryFrontend:
          replicas: 1
        compactor:
          replicas: 1
        memcached:
          enabled: false
        minio:
          enabled: false
        tempo:
          storage:
            trace:
              backend: local
              local:
                path: /var/tempo/traces
          ingester:
            lifecycler:
              ring:
                replication_factor: 1
          distributor:
            receivers:
              otlp:
                protocols:
                  grpc:
                    endpoint: 0.0.0.0:4317
                  http:
                    endpoint: 0.0.0.0:4318
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true