apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: tracing
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo:3200
        uid: tempo
        jsonData:
          tracesToLogs:
            datasourceUid: loki
            tags: ["job"]
            mappedTags:
              - key: service.name
                value: job
            filterByTraceID: false
            filterBySpanID: false
            spanStartTimeShift: "-1m"
            spanEndTimeShift: "1m"
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        uid: loki
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        uid: prometheus
        isDefault: false
        jsonData:
          exemplarTraceIdDestinations:
            - name: trace_id
              datasourceUid: tempo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: tracing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin
        volumeMounts:
        - name: datasources
          mountPath: /etc/grafana/provisioning/datasources
      volumes:
      - name: datasources
        configMap:
          name: grafana-datasources
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: tracing
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
  type: NodePort